### Generated by rprotoc. DO NOT EDIT!
### <proto file: test/fixtures/proto/addressbook_ext.proto>
# import "test/fixtures/proto/addressbook_base.proto";
# package tutorial;
# 
# extend Person {
#   optional int32 age = 100;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

require 'test/fixtures/addressbook_base.rb'
module Tutorial
  class Person < ::Protobuf::Message
    defined_in __FILE__
    optional :int32, :age, 100, :extension => true
  end
end